import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/navigation/header";
import HeaderMobile from "./components/navigation/header-mobile.tsx";
import SideNav from "./components/navigation/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen">
          <Header></Header>
          <div className="flex items-center justify-center" style={{ height: 'calc(100vh - 50px)' }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
